# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'First.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from __future__ import print_function
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from PyQt5.QtGui import QPixmap
from PIL import Image
import numpy as np
from skimage.data import shepp_logan_phantom
from skimage.transform import radon, rescale, iradon
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import (NavigationToolbar2QT as NavigationToolbar)
import matplotlib.image as img

class Ui_GroupBox(object):
    def setupUi(self, GroupBox):
        GroupBox.setObjectName("GroupBox")
        GroupBox.resize(1247, 772)
        self.labelSheppLogan = MplWidget(GroupBox)
        self.labelSheppLogan.setGeometry(QtCore.QRect(10, 10, 271, 261))
        self.labelSheppLogan.setObjectName("labelSheppLogan")
        self.labelSinogram = MplWidget(GroupBox)
        self.labelSinogram.setGeometry(QtCore.QRect(380, 10, 271, 261))
        self.labelSinogram.setObjectName("labelSinogram")
        self.labelLaminogramStep20 = MplWidget(GroupBox)
        self.labelLaminogramStep20.setGeometry(QtCore.QRect(750, 10, 271, 261))
        self.labelLaminogramStep20.setObjectName("labelLaminogramStep20")
        self.labelLaminogramStep1 = MplWidget(GroupBox)
        self.labelLaminogramStep1.setGeometry(QtCore.QRect(10, 370, 271, 261))
        self.labelLaminogramStep1.setObjectName("labelLaminogramStep1")
        self.labelLaminogramRamLak = MplWidget(GroupBox)
        self.labelLaminogramRamLak.setGeometry(QtCore.QRect(380, 370, 271, 261))
        self.labelLaminogramRamLak.setObjectName("labelLaminogramRamLak")
        self.labelLaminogramHamming = MplWidget(GroupBox)
        self.labelLaminogramHamming.setGeometry(QtCore.QRect(750, 370, 271, 261))
        self.labelLaminogramHamming.setObjectName("labelLaminogramHamming")
        self.label = QtWidgets.QLabel(GroupBox)
        self.label.setGeometry(QtCore.QRect(790, 280, 211, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(GroupBox)
        self.label_2.setGeometry(QtCore.QRect(90, 290, 111, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(GroupBox)
        self.label_3.setGeometry(QtCore.QRect(80, 650, 181, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(GroupBox)
        self.label_4.setGeometry(QtCore.QRect(510, 290, 61, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(GroupBox)
        self.label_5.setGeometry(QtCore.QRect(420, 650, 181, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(GroupBox)
        self.label_6.setGeometry(QtCore.QRect(800, 650, 201, 20))
        self.label_6.setObjectName("label_6")

        self.retranslateUi(GroupBox)
        QtCore.QMetaObject.connectSlotsByName(GroupBox)
        self.backprojection()
        
        
    def backprojection(self):
        img = shepp_logan_phantom()
        self.labelSheppLogan.canvas.axes.imshow(img, cmap='gray')
        self.labelSheppLogan.canvas.draw()
        theta = np.linspace(0, 180, max(img.shape), endpoint=False,dtype=np.uint8) # number of samples to be generated
        theta_1 = np.arange(0,160,20)
        sinogram = radon(img, theta=theta)
        sinogram_1 = radon(img, theta=theta_1)
        self.labelSinogram.canvas.axes.imshow(sinogram, cmap='gray')
        self.labelSinogram.canvas.draw()
        lamm= iradon(sinogram_1, theta=theta_1, filter_name=None)
        self.labelLaminogramStep20.canvas.axes.imshow(lamm, cmap='gray')
        self.labelLaminogramStep20.canvas.draw()
        self.labelLaminogramStep1.canvas.axes.imshow(iradon(sinogram, filter_name=None), cmap='gray')
        self.labelLaminogramStep1.canvas.draw()
        self.labelLaminogramRamLak.canvas.axes.imshow(iradon(sinogram, theta=theta, filter_name='ramp'), cmap='gray')
        self.labelLaminogramRamLak.canvas.draw()
        self.labelLaminogramHamming.canvas.axes.imshow(iradon(sinogram, theta=theta, filter_name='hamming'), cmap='gray')
        self.labelLaminogramHamming.canvas.draw()

    def retranslateUi(self, GroupBox):
        _translate = QtCore.QCoreApplication.translate
        GroupBox.setWindowTitle(_translate("GroupBox", "GroupBox"))
        self.label.setText(_translate("GroupBox", "Laminogram with step 20 degree"))
        self.label_2.setText(_translate("GroupBox", "Original phantom"))
        self.label_3.setText(_translate("GroupBox", "Laminogram with step 1"))
        self.label_4.setText(_translate("GroupBox", "Sinogram"))
        self.label_5.setText(_translate("GroupBox", "Laminogram with Ram-Lak filter"))
        self.label_6.setText(_translate("GroupBox", "Laminogram with Hamming filter"))
from mplwidget import MplWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GroupBox = QtWidgets.QGroupBox()
    ui = Ui_GroupBox()
    ui.setupUi(GroupBox)
    GroupBox.show()
    sys.exit(app.exec_())
